# Generated by Django 4.2.6 on 2023-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('img', models.ImageField(upload_to='', verbose_name='изображение')),
                ('number_of_views', models.IntegerField(verbose_name='количество просмотров')),
                ('date_of_published', models.DateField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блогы',
            },
        ),
    ]
