# Generated by Django 4.2.6 on 2023-10-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(choices=[('D', 'day'), ('W', 'week'), ('M', 'month')], default='D', max_length=1)),
                ('status', models.CharField(choices=[('COM', 'completed'), ('CRE', 'created'), ('LAU', 'launched')], default='CRE', max_length=3, verbose_name='статус рассылки')),
            ],
        ),
    ]
