# Generated by Django 4.2.6 on 2023-10-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='name',
            field=models.CharField(default='Рассылка', max_length=150, verbose_name='название рассылки'),
        ),
    ]
