# Generated by Django 4.2.6 on 2023-10-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailings_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
