# Generated by Django 4.2.6 on 2023-10-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailings_user_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mailings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailings.mailings'),
        ),
    ]
