# Generated by Django 4.2.6 on 2023-10-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_remove_message_mailings_mailings_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='periodicity',
            field=models.CharField(choices=[('Раз в день', 'day'), ('Раз в неделю', 'week'), ('Раз в месяц', 'month')], default='Раз в день', max_length=15),
        ),
    ]
