# Generated by Django 4.2.6 on 2023-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_alter_mailings_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(choices=[('Запущена', 'completed'), ('Создана', 'created'), ('Законченна', 'launched')], default='Создана', max_length=15, verbose_name='статус рассылки'),
        ),
    ]
