# Generated by Django 4.2.6 on 2023-10-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0011_alter_mailings_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='message',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='mailings.message'),
        ),
    ]
