# Generated by Django 4.2.6 on 2023-10-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0012_alter_mailings_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mailings.client'),
        ),
    ]
