# Generated by Django 4.2.6 on 2023-10-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0013_mailings_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailings',
            name='client',
        ),
        migrations.AddField(
            model_name='mailings',
            name='client',
            field=models.ManyToManyField(to='mailings.client'),
        ),
    ]
