# Generated by Django 4.2.6 on 2023-10-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0015_remove_mailings_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='clients',
            field=models.ManyToManyField(to='mailings.client'),
        ),
    ]
