# Generated by Django 4.2.6 on 2023-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0016_mailings_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='user_creator',
            field=models.CharField(max_length=150, verbose_name='создатель'),
        ),
    ]
