# Generated by Django 4.2.6 on 2023-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0022_intersectionmailingsclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='time_to_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
