# Generated by Django 4.2.6 on 2023-10-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0023_mailings_time_to_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='time_to_send',
            field=models.TimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
