# Generated by Django 4.2.6 on 2023-10-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('mailings', '0024_alter_mailings_time_to_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersectionmailingsclients',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='clients',
            field=models.ManyToManyField(to='clients.client', verbose_name='клиенты'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
