# Generated by Django 4.2.6 on 2023-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0025_alter_intersectionmailingsclients_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время рассылки')),
                ('mailings_title', models.CharField(blank=True, null=True, verbose_name='имя рассылки')),
                ('mailing_text', models.TextField(blank=True, null=True, verbose_name='текст рассылки')),
                ('success', models.BooleanField(default=False, verbose_name='успешность отправки')),
            ],
        ),
    ]
