# Generated by Django 4.2.6 on 2023-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0029_rename_mailings_title_logmailings_mailings_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmailings',
            name='user_created',
            field=models.CharField(blank=True, null=True, verbose_name='создатель рассылки'),
        ),
    ]
