# Generated by Django 4.2.6 on 2023-10-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0031_mailings_day_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'permissions': [('set_status', 'может менять статус')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
